apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
resources:
- postgresql-data-pvc.yaml
- postgresql-dc.yaml
- postgresql-svc.yaml
- sonarqube-data-pvc.yaml
- sonarqube-dc.yaml
- sonarqube-is.yaml
- sonarqube-route.yaml
- sonarqube-svc.yaml
patchesJson6902:
- target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: sonarqube
  path: plugins-patches.yaml