apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: sonarqube
    app.kubernetes.io/component: sonarqube-is
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/part-of: sonarqube
  name: sonarqube
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: The SonarQube Docker image
      tags: sonarqube
    from:
      kind: DockerImage
      name: sonarqube:8.2-community
    importPolicy: {}
    name: "8.2-community"
    referencePolicy:
      type: Source
