apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/pittar-sandbox/decisionmaker
  labels:
    app: decisionmaker
    app.kubernetes.io/component: decisionmaker
    app.kubernetes.io/instance: decisionmaker
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: gameoflife
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  name: decisionmaker
  namespace: gameoflife
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: decisionmaker:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/pittar-sandbox/decisionmaker
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-11-el7
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
