apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jenkins-dc.yaml
- jenkins-jnlp.yaml
- jenkins-pvc.yaml
- jenkins-rolebinding.yaml
- jenkins-route.yaml
- jenkins-sa.yaml
- jenkins-svc.yaml
- jenkins-cm.yaml
- maven-m2-pvc.yaml
- nexus-secret.yaml
- image-puller-rolebinding.yaml
generatorOptions:
  labels:
    app: jenkins
    app.kubernetes.io/component: maven-settings-cm
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/part-of: jenkins
  disableNameSuffixHash: true
configMapGenerator:
- name: maven-settings-cm
  files:
  - settings.xml
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cicd-image-puller
    path: image-puller-subjects-patch.yaml